// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using merchantapp.Infrastructure.Context;

#nullable disable

namespace merchantapp.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260331113109_AlignExistingMerchantDb")]
    partial class AlignExistingMerchantDb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("merchant.domain.Entities.ExchangeRateSnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("EurToTryRate")
                        .HasColumnType("decimal(18,4)");

                    b.Property<DateTime?>("FetchedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<decimal?>("UsdToTryRate")
                        .HasColumnType("decimal(18,4)");

                    b.HasKey("Id");

                    b.ToTable("ExchangeRateSnapshots", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("b3e8a998-1cc0-448f-a0d1-61fbfcf88d57"),
                            EurToTryRate = 41.9500m,
                            FetchedAtUtc = new DateTime(2026, 3, 31, 9, 0, 0, 0, DateTimeKind.Utc),
                            Source = "Static seed",
                            UsdToTryRate = 38.6500m
                        });
                });

            modelBuilder.Entity("merchant.domain.Entities.MerchantApplicationHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.Property<string>("HistoryDescription")
                        .IsRequired()
                        .HasColumnType("varchar(500)");

                    b.Property<Guid>("MerchantApplicationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ProcessDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("varchar(30)");

                    b.Property<string>("UserCode")
                        .IsRequired()
                        .HasColumnType("varchar(30)");

                    b.HasKey("Id");

                    b.HasIndex("MerchantApplicationId");

                    b.ToTable("MerchantApplicationHistories", (string)null);
                });

            modelBuilder.Entity("merchant.domain.Entities.MerchantDocument", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("DocumentType")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint");

                    b.Property<Guid>("MerchantApplicationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasColumnType("varchar(260)");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("MerchantApplicationId");

                    b.ToTable("MerchantDocuments", (string)null);
                });

            modelBuilder.Entity("merchant.domain.Entities.MerchantDocumentType", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.ToTable("MerchantDocumentTypes", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DisplayOrder = 1,
                            IsRequired = true,
                            Name = "Vergi Levhasi"
                        },
                        new
                        {
                            Id = 2,
                            DisplayOrder = 2,
                            IsRequired = true,
                            Name = "Imza Sirkuleri"
                        },
                        new
                        {
                            Id = 3,
                            DisplayOrder = 3,
                            IsRequired = true,
                            Name = "Ticaret Sicil Gazetesi"
                        },
                        new
                        {
                            Id = 4,
                            DisplayOrder = 4,
                            IsRequired = true,
                            Name = "Kimlik"
                        },
                        new
                        {
                            Id = 5,
                            DisplayOrder = 5,
                            IsRequired = true,
                            Name = "Uye Isyeri Sozlesmesi"
                        });
                });

            modelBuilder.Entity("son_calisma_merchantapp.Entities.Merchantdetails", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ApplicationNumber")
                        .IsRequired()
                        .HasColumnType("varchar(30)");

                    b.Property<string>("ApplicationStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar(20)")
                        .HasDefaultValue("Onay Bekliyor");

                    b.Property<string>("BranchCode")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.Property<string>("BranchName")
                        .IsRequired()
                        .HasColumnType("varchar(150)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("CompanyType")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("ContractedUserCode")
                        .IsRequired()
                        .HasColumnType("varchar(30)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CustomerAddress")
                        .IsRequired()
                        .HasColumnType("varchar(500)");

                    b.Property<string>("CustomerNumber")
                        .IsRequired()
                        .HasColumnType("varchar(30)");

                    b.Property<string>("DemandDepositAccountNumber")
                        .IsRequired()
                        .HasColumnType("varchar(34)");

                    b.Property<string>("District")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(150)");

                    b.Property<string>("GsmNumber")
                        .IsRequired()
                        .HasColumnType("varchar(15)");

                    b.Property<string>("IdentityNumber")
                        .IsRequired()
                        .HasColumnType("varchar(11)");

                    b.Property<bool>("IsSpecialRulingRequired")
                        .HasColumnType("bit");

                    b.Property<decimal>("Latitude")
                        .HasColumnType("decimal(9,6)");

                    b.Property<decimal>("Longitude")
                        .HasColumnType("decimal(9,6)");

                    b.Property<string>("ManagerFullName")
                        .IsRequired()
                        .HasColumnType("varchar(150)");

                    b.Property<string>("OwnerFullName")
                        .IsRequired()
                        .HasColumnType("varchar(150)");

                    b.Property<string>("OwnerIdentityNumber")
                        .IsRequired()
                        .HasColumnType("varchar(11)");

                    b.Property<string>("OwnerMobilePhone")
                        .IsRequired()
                        .HasColumnType("varchar(15)");

                    b.Property<string>("PosInstallationAddress")
                        .IsRequired()
                        .HasColumnType("varchar(500)");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasColumnType("varchar(10)");

                    b.Property<string>("TaxNumber")
                        .IsRequired()
                        .HasColumnType("varchar(10)");

                    b.Property<string>("TaxOffice")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("TradeRegistryNumber")
                        .IsRequired()
                        .HasColumnType("varchar(30)");

                    b.Property<DateTime?>("TradeRegistryRegistrationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("TradeRegistryRegistrationName")
                        .IsRequired()
                        .HasColumnType("varchar(150)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("WebAddress")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("WorkflowReferenceNumber")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("WorkplaceSignboardName")
                        .IsRequired()
                        .HasColumnType("varchar(150)");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationNumber")
                        .IsUnique();

                    b.HasIndex("TaxNumber")
                        .IsUnique();

                    b.ToTable("MerchantApplications", (string)null);
                });

            modelBuilder.Entity("merchant.domain.Entities.MerchantApplicationHistory", b =>
                {
                    b.HasOne("son_calisma_merchantapp.Entities.Merchantdetails", "MerchantApplication")
                        .WithMany("Histories")
                        .HasForeignKey("MerchantApplicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MerchantApplication");
                });

            modelBuilder.Entity("merchant.domain.Entities.MerchantDocument", b =>
                {
                    b.HasOne("son_calisma_merchantapp.Entities.Merchantdetails", "MerchantApplication")
                        .WithMany("Documents")
                        .HasForeignKey("MerchantApplicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MerchantApplication");
                });

            modelBuilder.Entity("son_calisma_merchantapp.Entities.Merchantdetails", b =>
                {
                    b.Navigation("Documents");

                    b.Navigation("Histories");
                });
#pragma warning restore 612, 618
        }
    }
}
